Repository falcosecurity/community, pull requests merged in 2019-10, with the labels that each got.

#43 Meeting minutes (2th Oct 2019)
  meeting-notes/2019-Oct-02.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#44 Adding live stream framework
  live-streams/README.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#45 update(meeting-notes): filenames with YYYY-MM-DD format
  meeting-notes/2019-06-06.md
  meeting-notes/2019-06-13.md
  meeting-notes/2019-06-20.md
  meeting-notes/2019-06-28.md
  meeting-notes/2019-07-04.md
  meeting-notes/2019-07-11.md
  meeting-notes/2019-07-25.md
  meeting-notes/2019-08-01.md
  meeting-notes/2019-09-04.md
  meeting-notes/2019-10-02.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#48 Adding meeting notes from repo planning call 10/9/2019
  meeting-notes/2019-10-09.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#49 Add October 16th 2019
  meeting-notes/2019-10-16.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#47 Adding notes from stream
  live-streams/001-opa-gatekeeper/README.md
  live-streams/config/NovaArchlinuxLaptop.profile/basic.ini
  live-streams/config/NovaArchlinuxLaptop.profile/service.json
  live-streams/config/NovaArchlinuxLaptop.scene
Labels: approved, dco-signoff: yes, lgtm, size/XXL
