Repository falcosecurity/community, pull requests merged in 2020-01, with the labels that each got.

#65 new: add meeting minutes for Jan 8th 2020
  meeting-notes/2020-01-08.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#69 Updating Community Repo
  DEBUGGING_HOURS.md
  README.md
  logo/primary-logo.png
  logo/teal-logo.png
  logo/white-logo.png
  meeting-notes/new-contributor-2020-02-21.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#70 new: meeting minutes for community call (22th Jan 2020)
  meeting-notes/2020-01-22.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#62 update: OWNERS
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, size/XS
