Repository falcosecurity/community, pull requests merged in 2020-11, with the labels that each got.

#124 update: calendar UTC
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#125 docs(meeting-notes): meeting minutes for November 11th 2020
  meeting-notes/2020-11-11.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#126 recording for community call 2020-11-11
  meeting-notes/2020-11-11.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#127 update: add Spencer to OWNERS
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, size/XS
