Repository falcosecurity/community, pull requests merged in 2020-02, with the labels that each got.

#72 Meeting notes - Call 2020 01 29
  meeting-notes/2020-01-21-new-contributors.md
  meeting-notes/2020-01-22.md
  meeting-notes/2020-01-28-build-release.md
  meeting-notes/2020-01-29.md
Labels: approved, dco-signoff: yes, do-not-merge/hold, lgtm, size/M

#73 Updating community issues to be more welcoming
  .github/ISSUE_TEMPLATE/debugging_hours.md
  .github/ISSUE_TEMPLATE/discuss_issue.md
  .github/ISSUE_TEMPLATE/discuss_pull_request.md
  .github/ISSUE_TEMPLATE/welcome.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#76 new: meeting minutes for infra call 13th february 2020
  meeting-notes/2020-02-13-infrastructure.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#78 new(meeting-notes): 2020 02 19 community call
  meeting-notes/2020-02-19.md
Labels: approved, dco-signoff: yes, lgtm, size/L
